lab_eqpt = ['safety goggles', 'safety equipment', 'beakers', 'erlenmeyer flasks', 'conical flasks', 'florence flasks' , 'boiling flasks', 'tube', 'flask', 'test tubes', 
'tongs', 'racks', 'watch glasses', 'crucibles', 'funnels', 'graduated cylinders', 'volumetric flasks', 'droppers', 'pipettes', 'burets', 'ring stands', 'rings', 
'clamps', 'forceps', 'spatulas', 'scoopulas', 'thermometers', 'bunsen burners', 'balances', 'acetic acid', 'CH3COOH', 'H2O', 'white vinegar', 'acetone', 'CH3COCH3', 'fiberglass cleaner', 
'acetylene gas', 'C2H2', 'ethyne', 'calcium carbide', 'water', 'acetylsalicylic acid', 'C9H8O4', 'aspirin', 'aluminium', 'bauxite', 'hydroxide', 'Al(OH)3','alumina', 'hydrate', 'antacid', 'magnesium', 'oxide', 
'antacid', 'alu-cap', 'amphojel', 'dialume', 'Al2O3', 'grinding agent', 'optical components', 'lapidary', 'ammonium', 'sulfate', 'pipette',
'AlNH4(SO4)2', 'chemical', 'potassium', 'KAl(SO4)2 • 12H2O','Al2(SO4)3', 'ammonia', 'NH3(aq)', 'NH4OH', 
'anhydrous', 'cylinders', 'bicarbonate', 'bifluoride', 'bromide', 'carbonate', 'salt', 'chloride', 'ammoniac', 'nitrate', 'persulfate', 'peroxodisulphate', 'phosphate', 'pH',
'amylose', 'corn starch', 'anthocyanin', 'argon', 'gas', 'ascorbic', 'acid', 'formula','barium', 'carbonate', 'lithopone',	'zinc', 'radiology', 'lab equipment', 'lab supplies',
'benzoyl', 'peroxide', 'bismuth', 'metal', 'subsalicylate',	'pepto-bismol', 'kaopectate', 'boric', 'bromothymol',
'butane', 'cadmium', 'sulfide', 'calcium', 'carbide', 'acetylene', 'antacids', 'hydroxide', 'hypochlorite', 'cyanuric', 'stabilizer',
'nitrate', 'oxide', 'quicklime', 'phosphate', 'monobasic', 'superphosphate', 'hemihydrate', 'dihydrate', 'camphor', 'carbon',
'graphite', 'graphene', 'nanotubes', 'fullerenes', 'charcoal', 'briquettes', 'additives', 'batteries', 'dioxide', 'carbonic', 'carrageenan',
'thickener', 'gelling agent', 'cellulose', 'chromium', 'polishing metal', 'citric', 'copper', 'pipe', 'naphthenate', 'cupric', 'petroleum',
'distillate', 'solvents', 'pentahydrate', 'vitriol', 'active ingredient', 'algaecides', 'cyanuric', 'isocyanuric', 'chlorine', 'stabilizer',
'dextrose', 'glucose', 'dichloromethane', 'methylene', 'solvent', 'degreaser', 'dimethyl', 'sulfoxide', 'ethanol', 'ethyl', 'alcohol', 'ether',
'diethyl', 'ethoxyethane', 'ethylene', 'glycol', 'ethanediol', 'eugenol', '2-methoxy-4-(2-propenyl)phenol', 'formic acid', 'methanoic', 'fructose', 'dextrose', 'glycerin', 'glycerol',	'propanetriol', 'emollient', 
'helium', 'hexamine', 'hexamethylenetetramine', 'trioxane', 'hydrogen', 'hydrochloric', 'muriatic', 'platinum', 'anodes', 'cathodes', 
'hydrofluoric', 'polyethylene', 'container', 'gluconate', 'gel', 'hypochlorous', 'hydroquinone', 'peroxide', 'antiseptic',
'iodine', 'methamphetamine', 'iron', 'ferric', 'ferrous', 'ferric', 'kerosene', 'lanthanum', 'aqueous', 'latex', 'lead', 'linseed oil',
'lithium', 'magnesium', 'antacid', 'silicate', 'talc', 'mercury', 'methane', 'methanol', 'solvent', 'ketone', 'catalyst', 'polyester', 'resins',
'isobutyl', 'methidote', 'salicylate', 'monosodium', 'sodium', 'glutamate', 'naphthalene', 'dichlorobenzene', 'nickel', 'nitrogen', 'gaseous',
'oxalic', 'oxygen', 'para-dichlorobenzene', 'paraffin', 'sealant', 'phenol', 'phenolphthalein', 'thymolphthalein', 'phenolsulfonephthalein', 
'phosphoric', 'polystyrene', 'polyurethane', 'potassium', 'bitartrate', 'bromide', 'salt', 'dichromate', 'hexacyanoferrate', 'ferricyanide', 
'ferroferricyanide', 'sulfites', 'iodide', 'metabisulfite', 'sterilizing agent','permanganate', 'tartrate', 'propane',
'propanol', 'silicon', 'silica', 'silver', 'acetate', 'borate', 'disodium', 'bisulfate', 'chlorate', 'fluoride', 'hexametaphosphate',
'polymetaphosphate', 'hypochlorite', 'percarbonate', 'peroxyhydrate', 'tetraborate', 'decahydrate', 'thiosulfate', 'additive',
'stearic', 'steel', 'vanadium','boron', 'titanium', 'manganese', 'tungsten', 'sulfur', 'sulphur', 'tetrachloroethylene',
'thymolphthalein', 'trichloroethane', 'tetrafluoroethane', 'thiourea', 'toluene', 'methylbenzene', 'trichloroethylene', 'urea', 'distilled', 
'deionized', 'xylene',	'dimethylbenzene', 'methyl', 'dimethylsiloxane', 'polymer', 'bromomethyl', 'propene', 'acrylate', 'methacrylate', 
'ammonium', 'dibromo']